

export enum ErrorStatus {
    DEVICE_INFO_NOT_MATCHED = -100,
    USER_NOT_REGISTERED = -104,
    PHONE_NUMBER_NOT_VALID = -101,
    CODE_NOT_MATCHED = -102,
    PHONE_NUMBER_ALREADY_EXIST = -103,
    NEAR_DISTRICT_NOT_FOUND = -110,
    FILE_NOT_FOUND = -120,
}